name: Repo tests CPP

on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  os-repo-tests:
    env:
      VDB_DATABASE_URL: "ghcr.io/appthreat/vdbxz-app-2y:v6.7.x"
    strategy:
      fail-fast: false
      matrix:
      # TODO: Restore all the OS and python versions
        os: ['ubuntu-24.04']
        python-version: ['3.14']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          repository: 'microsoft/Attestation-Client-Samples'
          path: 'repotests/attestation-client-samples'
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: '24.x'
          package-manager-cache: false
      - name: Setup Cpp
        uses: aminya/setup-cpp@1f17f92d6a52bfcb1a25348e2c526c2e5cbb1134  # v1.8.0
        with:
          compiler: llvm
          cmake: true
          vcpkg: true
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Trim CI agent
        run: |
          chmod +x contrib/free_disk_space.sh
          ./contrib/free_disk_space.sh
      - name: Install depscan
        run: |
          uv sync --all-extras --all-packages --dev
          npm install -g @cyclonedx/cdxgen
      # LifeCycleAnalyzer tests
      - name: lifecycle-test attestation-client-samples
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/depscan_reports/attestation-client-samples
          uv run depscan --src ${GITHUB_WORKSPACE}/repotests/attestation-client-samples\
                          --reports-dir ${GITHUB_WORKSPACE}/depscan_reports/attestation-client-samples\
                          -t cpp\
                          --vulnerability-analyzer LifecycleAnalyzer
        shell: bash
        env:
          BLINTDB_HOME: ${{ runner.temp }}/blintdb-home
