name: Repo tests Dotnet (WIP)

on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  os-repo-tests:
    env:
      VDB_DATABASE_URL: "ghcr.io/appthreat/vdbxz-app-2y:v6.7.x"
    strategy:
      fail-fast: false
      matrix:
      # TODO: Restore all the OS and python versions
        os: ['ubuntu-24.04']
        python-version: ['3.14']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          repository: 'Nova-8/Damm-Vulnerable-dotNet-Application'
          path: 'repotests/Damm-Vulnerable-dotNet-Application'
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: '24.x'
          package-manager-cache: false
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68  # v6.0.0
        with:
          dotnet-version: '6.x'
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Trim CI agent
        run: |
          chmod +x contrib/free_disk_space.sh
          ./contrib/free_disk_space.sh
      - name: Install depscan
        run: |
          uv sync --all-extras --all-packages --dev
          npm install -g @cyclonedx/cdxgen
          sudo apt install -y libssl-dev
      # LifeCycleAnalyzer tests
      - name: lifecycle-test Damm-Vulnerable-dotNet-Application
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/depscan_reports/Damm-Vulnerable-dotNet-Application
          dotnet build ${GITHUB_WORKSPACE}/repotests/Damm-Vulnerable-dotNet-Application/WebGoat.NET.sln
          uv run depscan --src ${GITHUB_WORKSPACE}/repotests/Damm-Vulnerable-dotNet-Application\
                          --reports-dir ${GITHUB_WORKSPACE}/depscan_reports/Damm-Vulnerable-dotNet-Application\
                          -t dotnet\
                          --vulnerability-analyzer LifecycleAnalyzer
        shell: bash
        env:
          BLINTDB_HOME: ${{ runner.temp }}/blintdb-home
